version: '3'

services:
    #Service 1
    deploy: 
      build: ./app
      volumes:
        - ./app:/app
      container_name: APPLICATION
      restart: on-failure
      expose:
        - 8080
        - 2021
   
    nginx:
      build: ./nginx
      container_name: NGINX
      depends_on:
        - deploy
      restart: on-failure
      ports:
        - "80:80"
       