version: '3'

services:
    #Service 1
    deploy: 
      build: ./app
      volumes:
        - ./app:/app
      container_name: app
      restart: on-failure
      expose:
        - 2021
         #hostport:containerport

    nginx:
      build: ./nginx
      container_name: nginx
      restart: on-failure
      ports:
        - "80:80"