# Choosing python image
FROM python:3-onbuild

# Copy the app to the image's working directory
COPY . /usr/src/app

#EXPOSE 2021/ this will be specified in docker-compose.yml

# Run the app
CMD  ["python3", "run.py"]